services:
    maintenance.listener:
        class: NDC\MaintenanceBundle\Event\MaintenanceListener
        arguments: ['%kernel.root_dir%', '@twig', '@maintenance.service']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    maintenance.service:
        class: NDC\MaintenanceBundle\Service\MaintenanceManager
        arguments: ['%kernel.root_dir%']

    maintenance.twig_extension:
        class: NDC\MaintenanceBundle\Twig\AppExtension
        arguments: ['%kernel.root_dir%']
        tags:
            - { name: twig.extension }
